[phases.setup]
nixPkgs = ['python3', 'python3Full', 'gcc', 'libcxx', 'zlib', 'openssl']

[phases.install]
commands = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
command = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"