[phases.setup]
nixPkgs = ['python3', 'python3Full']

[phases.install]
commands = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
command = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"